### ISSUE TITLE
Lines to be commented out and ambiguous instructions

### ISSUE THREAD

**Issue by exfalsoquodlibet** [alphagov/docker-for-data-apps#1]
Thanks Max, this was great.

A couple of things in the Dockerfile:
-  lines 28-29 should be commented out, otherwise when you copy the file content, they raise an Error  https://github.com/alphagov/docker-for-data-apps/blob/55e45545b90e17a1c26a6147cd7941286a7ecf5b/Dockerfile#L28
- lines 20-21 instructions are ambiguous as it is not clear which of the two commands one has to run (I assume it is the second one) https://github.com/alphagov/docker-for-data-apps/blob/55e45545b90e17a1c26a6147cd7941286a7ecf5b/Dockerfile#L20

**Comment by maxf** [comment]
Thanks for the report. [All fixed](https://github.com/alphagov/docker-for-data-apps/commit/45d7248d8b62dddd5b0800c28be819971048806a) now
